version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"

  authentication-service:
    build:
      context: .
      dockerfile: ./authentication-service/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  file-service:
    build:
      context: .
      dockerfile: ./file-service/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: file_service_db
      POSTGRES_USER: file_service_user
      POSTGRES_PASSWORD: file_service_password

volumes:
  mongodb_data:
  postgresql_data: